PREFIX drafter: <http://publishmydata.com/def/drafter/>

# Migration to backfill versions on DraftSets and the public Endpoint

WITH <http://publishmydata.com/graphs/drafter/drafts>
INSERT {
  ?ds drafter:version ?version
} WHERE {
  VALUES ?endpoint_type { drafter:Endpoint drafter:DraftSet }

  ?ds a ?endpoint_type .
  OPTIONAL { ?ds drafter:version ?existing_version }
  BIND(uuid() AS ?new_version )
  BIND(COALESCE(?existing_version, ?new_version) AS ?version)
}
