prefix dcterms: <http://purl.org/dc/terms/> 
prefix drafter: <http://publishmydata.com/def/drafter/> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix draft: <http://publishmydata.com/graphs/drafter/draft> 
prefix draftset: <http://publishmydata.com/def/drafter/draftset/> 

SELECT ?livemod ?draftmod WHERE {
  OPTIONAL {

    SELECT ?livemod WHERE {
      
      VALUES ?graph {
      }
      
      GRAPH <http://publishmydata.com/graphs/drafter/drafts> {
        ?graph a drafter:ManagedGraph ;
               drafter:isPublic true .
      }

      GRAPH <http://publishmydata.com/graphs/drafter/graph-modified-times> {
          ?graph dcterms:modified ?livemod .
      }
    }
  } OPTIONAL {
    SELECT ?draftmod WHERE {
      VALUES ?graph { }

      GRAPH <http://publishmydata.com/graphs/drafter/drafts> {
        ?graph a drafter:DraftGraph ;
            drafter:inDraftSet ?ds .
        ?lg drafter:hasDraft ?graph .
        <http://publishmydata.com/graphs/drafter/graph-modified-times> drafter:hasDraft ?dmg .
        ?dmg drafter:inDraftSet ?ds .
      }

      GRAPH ?dmg {
        ?graph dcterms:modified ?draftmod .
      }
    }
  }
} ORDER BY DESC(?livemod) DESC(?draftmod) LIMIT 1
