PREFIX drafter: <http://publishmydata.com/def/drafter/>

# NOTE: query takes no params

WITH <http://publishmydata.com/graphs/drafter/endpoints>
DELETE {
  drafter:public drafter:version ?old .
} INSERT {
  drafter:public drafter:version ?new .
} WHERE {
  BIND(
    IRI(CONCAT("http://publishmydata.com/def/drafter/version/", STRUUID()))
    AS ?new
  )
  # Insert a version even if there isn't an old one to delete.
  OPTIONAL {
    drafter:public drafter:version ?old .
  }
}
