language: clojure
jdk:
- oraclejdk8
env:
- SPARQL_QUERY_ENDPOINT="http://localhost:5820/drafter/query"
- DRAFTER_BACKEND="drafter.backend.sesame.remote"
- SPARQL_UPDATE_ENDPOINT="http://localhost:5820/drafter/update"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y git unzip build-essential apache2-utils wget bsdtar python-pip
  - ./travis/bootstrap_stardog.sh
before_script:
  - sleep 15
  - sudo /opt/stardog/stardog/bin/stardog-admin db create -n drafter  -t D -o strict.parsing=false -o query.all.graphs=true -o reasoning.type=none -- # create stardog dbs
