language: clojure
sudo: required
lein: 2.7.1
jdk:
- oraclejdk8
services:
  - mongodb
env:
  global:
  - STARDOG_VERSION='stardog-4.1.2'
before_install:
- sudo apt-get update
- sudo apt-get install -y git unzip build-essential apache2-utils wget bsdtar python-pip
- sudo chown -R travis ./travis/*
- sudo chmod +x ./travis/*
- sudo mkdir -p /etc/leiningen/
- sudo mv ./travis/profiles.clj /etc/leiningen/profiles.clj
- "./travis/bootstrap_stardog.sh"
before_script:
- sleep 15
- env JAVA_HOME=/usr/lib/jvm/java-8-oracle/bin/java /opt/stardog/stardog/stardog-4.1.2/bin/stardog-admin db create -n drafter  -t D -o strict.parsing=false -o query.all.graphs=true -o reasoning.type=none --
- sleep 10
script: travis_retry env JAVA_HOME=/usr/lib/jvm/java-8-oracle/bin/java lein test
after_success:
- env LEIN_SNAPSHOTS_IN_RELEASE=true lein uberjar
before_deploy:
- mkdir -p dist
- cp target/drafter.jar dist/drafter-$TRAVIS_BRANCH-latest.jar
- cp target/drafter.jar dist/drafter-private-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.jar
deploy:
  - provider: s3
    access_key_id: AKIAJZVFELTIBDDYV5OQ
    secret_access_key:
      secure: BIaToFo+lK7GB+/IQhEAR44Ix18+ykJt+HIR6uxzZi3WRDuAP+JjngPf+A9rwKQ3fooyAgNZLnIp4EP00rpJ+YfAdUeQzxpcJxeMeUgH0hAR7o8udMTujqBLsTjxwI7B8nZGUHpUpVZiAG4SWhgm7QaU/x5/tTSmGk9inO6SJQY=
    bucket: travis-drafter-jars
    local-dir: dist
    upload-dir: travis-$TRAVIS_BRANCH
    region: eu-west-1
    skip_cleanup: true
    on:
      repo: Swirrl/drafter
      branch: master
  - provider: releases
    api_key: "$RELEASE_OAUTH_TOKEN"
    file: "target/drafter.jar"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
