language: clojure
lein: 2.7.1
jdk:
- oraclejdk8
env:
  matrix:
  - SPARQL_QUERY_ENDPOINT="http://localhost:5820/drafter/query"
  - DRAFTER_BACKEND="drafter.backend.sesame.remote"
  - SPARQL_UPDATE_ENDPOINT="http://localhost:5820/drafter/update"
  global:
    secure: fanfSvB+Jqlm0+NsBOQbA2X3KpXV4IPeOZ4bqEm4hmhSBtzCn+cPCGQMCM3KFpcf3L/WtEuLe4TFWLikBaDZzxk9KB4pINxgX8+nG5aBErVpFuhSqYcCUCMHA5fNvy3/zT3F5UiJbLN6DhW5n/JhLau+CQZ2wOOdQBH2eXvslhY=
before_install:
- sudo apt-get update
- sudo apt-get install -y git unzip build-essential apache2-utils wget bsdtar python-pip
- sudo chown -R travis ./travis/bootstrap_stardog.sh
- sudo chmod +x ./travis/bootstrap_stardog.sh
- "./travis/bootstrap_stardog.sh"
- echo $AWS_ACCESS_KEY_ID
before_script:
- sleep 15
- sudo /opt/stardog/stardog/bin/stardog-admin db create -n drafter  -t D -o strict.parsing=false
  -o query.all.graphs=true -o reasoning.type=none --
