* Configuring Drafter

Drafter uses integrant for its configuration.  It contains a partial base [[/drafter/resources/drafter-base-config.edn][configuration]] inside its jar, and expects additional configuration to provided as EDN files via its command line.

These files will then be merged ontop of the internal base configuration in order (left to right).

This allows drafter configuration to be split up into profiles.  

Most notably drafters base configuration is only a partial configuration.  Which means it won't start without some extra required configuration that is used to specify the authentication method & user database.  

We typically provide this extra configuration on the command line as an extra file of integrant keys.

These partial configurations typically support:

1. auth0 authentication (pmd 4 and newer apps such as DEFRA's DRL app) via for the omni installed dev file [[../../package/install/drafter-dev-auth0.edn][drafter-dev-auth0.edn]]
2. Basic auth authentication with an in memory db (useful for dev) via for example the omni installed dev file [[../../package/install/drafter-dev-basic-auth-memory-db.edn][drafter-dev-basic-auth-memory-db.edn]]
3. Basic auth authentication with a mongo user database (pmd 3 legacy) via for example the file [[../../package/install/drafter-prod-pmd3-auth.edn][drafter-prod-pmd3-auth.edn]]

Additionally some of the integrant keys defined in [[/drafter/resources/drafter-base-config.edn][drafter-base-config.edn]] expect to receive their values via environment variables.  Using environment variables allows several processes to share the same value, which can be useful to ensure all processes in development are speaking to the same database etc.  The most important configuration items configured this way are `SPARQL_QUERY_ENDPOINT` and `SPARQL_UPDATE_ENDPOINT`.  Though it is now possible to override these values by providing the overrides in one of the edn files of configuration overrides.

** Launching drafter

To launch drafter you must now supply as a command line a file specifying 
the configuration of your authentication mode (and/or) overrides for any 
other aspects of the integrant system.

e.g. you may start it with a command like:

#+BEGIN_EXAMPLE
$ java -jar ./drafter.jar drafter-dev-basic-auth-memory-db.edn &
#+END_EXAMPLE

Or you might start it in auth0 mode with a file of endpoint overrides to override `SPARQL_QUERY_ENDPOINT` and `SPARQL_UPDATE_ENDPOINT`.

#+BEGIN_EXAMPLE
$ java -jar ./drafter.jar drafter-prod-auth0.edn endpoint.edn &
#+END_EXAMPLE

Some working example files to run drafter can be found in the omni configuration at [[../../package/install/][../../package/install]]

* Legacy config documentation

Below is some legacy documentation on configuring drafter.  It may still be useful; though the canonical source should currently be the edn files of config [[../../package/install/][../../package/install/]]

** Stardog

Drafter uses stardog for storing RDF data and accesses a remote Stardog instance through a Sesame SPARQL
repository. The location of the query and update endpoints for the Stardog database to use must be configured.

#+BEGIN_EXAMPLE
SPARQL_QUERY_ENDPOINT         REQUIRED http://$STARDOG_PORT_5820_TCP_ADDR:5820/${DATABASE_NAME:-pmd-data}/query
SPARQL_UPDATE_ENDPOINT        REQUIRED http://$STARDOG_PORT_5820_TCP_ADDR:5820/${DATABASE_NAME:-pmd-data}/update
#+END_EXAMPLE

** Common configuration

Configuration properties summary:

| Env Var                                 | Required | Default    | Description                                          |
|-----------------------------------------+----------+------------+------------------------------------------------------|
| SPARQL_QUERY_ENDPOINT                   | Yes      | N/A        | Backend SPARQL Query Endpoint (Stardog)              |
| SPARQL_UPDATE_ENDPOINT                  | Yes      | N/A        | Backend SPARQL Update Endpoint (Stardog)             |
| DRAFTER_HTTP_PORT                       | No       | 3001       | The HTTP port drafter listens on                     |
| DRAFTER_BATCHED_WRITE_SIZE              | No       | 10000      | Max size of write batches in triples                 |
| DRAFTER_TIMEOUT_QUERY_ENDPOINT_LIVE     | No       | 30 seconds | Live endpoint max query timeout                      |
| DRAFTER_TIMEOUT_QUERY_ENDPOINT_DRAFTSET | No       | 30 seconds | Draftset endpoint max query timeout                  |
| DRAFTER_USER_DB_NAME                    | Yes      |            | Specific user database in mongo backend user server  |
| DRAFTER_MONGO_USER_COLLECTION           | No       | users      | The collection in mongo backend that holds the users |
| DRAFTER_MONGO_HOST                      | Yes      |            | Hostname for backend mongo service                   |
| DRAFTER_MONGO_PORT                      | Yes      |            | Port for backend mongo service                       |
| DRAFTER_JWS_SIGNING_KEY                 | Yes      |            | Shared token for JWT signing                         |



*** Batch size

=DRAFTER_BATCHED_WRITE_SIZE=
Due to the limitations of the sesame SPARQL repository, large append or delete jobs must split the incoming data into batches
to be applied sequentially to the stardog database. The size of these batches can be configured - note that out-of-memory
errors can occur if the value is set too high.

** Examples

Some examples of supplying these properties are provided below:

As environment variables via a built application jar:

#+BEGIN_SRC shell
env DRAFTER_HTTP_PORT=3050 SPARQL_QUERY_ENDPOINT=http://localhost:5820/drafter-db/sparql/query SPARQL_UPDATE_ENDPOINT=http://localhost:5820/drafter-db/sparql/update java -jar target/drafter-0.1.0-SNAPSHOT-standalone.jar
#+END_SRC

** Configuring Timeouts

SPARQL queries may require a long time to be evaluated, so to maintain the
availability of the server, each SPARQL endpoint can be configured with a query
timeout. If the query timeout is exceeded during query execution, it will be
cancelled by the server. There are two types of query endpoint - live and draftset
and the query timeouts can be configured by the following environment variables:

#+BEGIN_EXAMPLE
DRAFTER_TIMEOUT_QUERY_ENDPOINT_LIVE
DRAFTER_TIMEOUT_QUERY_ENDPOINT_DRAFTSET
#+END_EXAMPLE

The corresponding values should be the query timeout period in seconds.

By default, endpoints have a query timeout of 30 seconds.

** Users Database

The type of user repository to use is configured by specifying the namespace containing the repository
definition.

*** Mongo

A repository which looks up users in a mongo db instance is defined in the `drafter.user.mongo` namespace:

=DRAFTER_USER_REPO_NS=drafter.user.mongo=

The name of the database containing the user collection must be specified:

=DRAFTER_USER_DB_NAME=pmd2_development=

The name of the user collection within the database can also be specified:

=DRAFTER_MONGO_USER_COLLECTION=publish_my_data_users=

If not specified the default collection name of 'users' will be used.

The location of the mongo database can also be specified as a host/port pair:

=DRAFTER_MONGO_HOST=mongoserver=
=DRAFTER_MONGO_PORT=8080=

if either the host or port is specified, both are required. If neither is specified the host will default to
=localhost= and the port to 27017 (the default mongo port).

*** In-memory

To use the in-memory user repository set the namespace to =drafter.user.memory-repository=:

=DRAFTER_USER_REPO_NS=drafter.user.memory-repository=

The memory repository loads its users from a =test-users.edn= file in the working directory so this must exist.

** User Token Signing Key

Drafter can be configured to authenticated users from a JSON Web Signing (JWS) token in the incoming request.
This token must be signed using the configured HMAC-SHA-256 key. This key should be specified by the
DRAFTER_JWS_SIGNING_KEY environment variable:

#+BEGIN_SRC shell :exports code
DRAFTER_JWS_SIGNING_KEY=secretkey
#+END_SRC

If the =DRAFTER_JWS_SIGNING_KEY= environment variable is not present, JWS token authentication will not be
available.

The signing key is also used to sign max-query-timeout parameters within SPARQL query requests allowing
privileged clients to override the endpoint maximum query timeout. If the signing key is not configured,
these parameters will be ignored and no clients will be allows to override query timeouts.

** System Properties

The following JVM system properties can be set to configure various
aspects of drafter.  This is not necessarily an exhaustive list:

| Property            | Default Value | Description                                                                                                                                                                |
|---------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| http.maxConnections | 20?           | The maximum number of HTTP connections allowed inside Apache HTTP Client instances.  Use this to configure the connection pool size inside our Sesame SPARQLRepository, if using drafter against a remote store. |
