PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX drafter: <http://publishmydata.com/def/drafter/>

DELETE {
    GRAPH ?dmg {
        ?dmg dcterms:modified ?olddmg .
        ?dg dcterms:modified ?olddraft .
    }
} WHERE {
    GRAPH ?dmg {
        ?dmg dcterms:modified ?olddmg .
        OPTIONAL { ?dg dcterms:modified ?olddraft . }
    }
} ;
INSERT DATA {
    GRAPH ?dmg {
        ?dmg dcterms:modified ?modified .
    }
}

