#!/bin/bash

set -o errexit

# start services
./.omni_cache/install/stardog/install/dev-start.sh

.circleci/wait-for-service localhost:5820

echo Stardog up

if [[ -d ./.omni_cache/install/mongodb ]]; then
    ./.omni_cache/install/mongodb/install/dev-start.sh
    echo Mongo up
fi
