version: "3.9"
services:
  stardog:
    image: "swirrl/stardog:6.2.3"
    ports:
      - "5820:5820"
    environment:
      - CREATE_DATABASE=drafter-dev-db
  mongo:
    image: "mongo:3.2"
    ports:
      - "27017:27017"
