version: "3.10"
services:
  stardog:
    image: "europe-west2-docker.pkg.dev/swirrl-devops-infrastructure-1/swirrl/\
            stardog:8.0.1"
    ports:
      - "5820:5820"
    environment:
      CREATE_DATABASE: drafter-dev-db,drafter-test-db
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
