version: "3.10"
services:
  stardog:
    image: swirrl/stardog:6.2.3-multi-dbs
    ports:
      - "5820:5820"
    environment:
      CREATE_DATABASE: drafter-dev-db,drafter-test-db
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
