* Configuring Drafter

Drafter uses [[https://github.com/juxt/aero][aero]] for its configuration.  This means it uses
environment variables (and/or java properties) to pass configuration
variables from the environment. The file config-settings.edn defines all configuration settings,
along with their types, default values and the locations they are loaded from.

** Stardog

Drafter uses stardog for storing RDF data and accesses a remote Stardog instance through a Sesame SPARQL
repository. The location of the query and update endpoints for the Stardog database to use must be configured.

#+BEGIN_EXAMPLE
SPARQL_QUERY_ENDPOINT         REQUIRED http://$STARDOG_PORT_5820_TCP_ADDR:5820/${DATABASE_NAME:-pmd-data}/query
SPARQL_UPDATE_ENDPOINT        REQUIRED http://$STARDOG_PORT_5820_TCP_ADDR:5820/${DATABASE_NAME:-pmd-data}/update
#+END_EXAMPLE

** Common configuration

*** Drafter port
The port drafter listens on can be configured with `DRAFTER_HTTP_PORT`. The default is port 3001.

#+BEGIN_EXAMPLE
DRAFTER_HTTP_PORT:            (default 3001)
#+END_EXAMPLE

*** Batch size
Due to the limitations of the sesame SPARQL repository, large append or delete jobs must split the incoming data into batches
to be applied sequentially to the stardog database. The size of these batches can be configured - note that out-of-memory
errors can occur if the value is set too high.

** Examples

Some examples of supplying these properties are provided below:

As environment variables via a built application jar:

env DRAFTER_HTTP_PORT=3050 SPARQL_QUERY_ENDPOINT=http://localhost:5820/drafter-db/sparql/query SPARQL_UPDATE_ENDPOINT=http://localhost:5820/drafter-db/sparql/update java -jar target/drafter-0.1.0-SNAPSHOT-standalone.jar

#+BEGIN_EXAMPLE
DRAFTER_BATCHED_WRITE_SIZE:   (default 10000)
** Configuring Timeouts

SPARQL queries may require a long time to be evaluated, so to maintain the
availability of the server, each SPARQL endpoint can be configured with a query
timeout. If the query timeout is exceeded during query execution, it will be
cancelled by the server. There are two types of query endpoint - live and draftset
and the query timeouts can be configured by the following environment variables:

#+BEGIN_SRC shell :exports code
DRAFTER_TIMEOUT_QUERY_ENDPOINT_LIVE
DRAFTER_TIMEOUT_QUERY_ENDPOINT_DRAFTSET
#+END_SRC

The corresponding values should be the query timeout period in seconds.

By default, endpoints have a query timeout of 30 seconds.

** Users Database

The type of user repository to use is configured by specifying the namespace containing the repository
definition.

*** Mongo

A repository which looks up users in a mongo db instance is defined in the `drafter.user.mongo` namespace:

`DRAFTER_USER_REPO_NS=drafter.user.mongo`

The name of the database containing the user collection must be specified:

`DRAFTER_USER_DB_NAME=pmd2_development`

The name of the user collection within the database can also be specified:

`DRAFTER_MONGO_USER_COLLECTION=publish_my_data_users`

If not specified the default collection name of 'users' will be used.

The location of the mongo database can also be specified as a host/port pair:
`DRAFTER_MONGO_HOST=mongoserver`
`DRAFTER_MONGO_PORT=8080`

if either the host or port is specified, both are required. If neither is specified the host will default to
`localhost` and the port to 27017 (the default mongo port).

*** In-memory

To use the in-memory user repository set the namespace to `drafter.user.memory-repository`:

`DRAFTER_USER_REPO_NS=drafter.user.memory-repository`

The memory repository loads its users from a `test-users.edn` file in the working directory so this must exist.

** User Token Signing Key

Drafter can be configured to authenticated users from a JSON Web Signing (JWS) token in the incoming request.
This token must be signed using the configured HMAC-SHA-256 key. This key should be specified by the
DRAFTER_JWS_SIGNING_KEY environment variable:

#+BEGIN_SRC shell :exports code
DRAFTER_JWS_SIGNING_KEY=secretkey
#+END_SRC

If the DRAFTER_JWS_SIGNING_KEY environment variable is not present, JWS token authentication will not be
available.

The signing key is also used to sign max-query-timeout parameters within SPARQL query requests allowing
privileged clients to override the endpoint maximum query timeout. If the signing key is not configured,
these parameters will be ignored and no clients will be allows to override query timeouts.

** System Properties

The following JVM system properties can be set to configure various
aspects of drafter.  This is not necessarily an exhaustive list:

| Property            | Default Value | Description                                                                                                                                                                |
|---------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| http.maxConnections | 20?           | The maximum number of HTTP connections allowed inside Apache HTTP Client instances.  Use this to configure the connection pool size inside our Sesame SPARQLRepository, if using drafter against a remote store. |
