PREFIX drafter: <http://publishmydata.com/def/drafter/>

ASK WHERE {
  GRAPH <http://publishmydata.com/graphs/drafter/drafts> {
    ?lg a drafter:ManagedGraph .
    ?lg drafter:hasDraft ?dg .
    ?dg drafter:inDraftSet ?ds .
    ?ds a drafter:DraftSet .
  }
}
