#!/bin/bash

set -e
set -o pipefail

if [ -z "${SPARQL_QUERY_ENDPOINT}" ] && [ -z "${SPARQL_UPDATE_ENDPOINT}" ] ; then
   echo You must set env vars for SPARQL_UPDATE_ENDPOINT and SPARQL_QUERY_ENDPOINT
   exit 1
fi

cd `dirname $0`

cd ../drafter

lein test
lein spec
env LEIN_SNAPSHOTS_IN_RELEASE=true lein uberjar

cp log-config.edn.example log-config.edn

# Run drafter-client tests against our in memory dev/users db
java -jar target/drafter.jar env/dev/resources/drafter-dev-config.edn

../stardog/bin/stardog-admin db create drafter-client-test
../stardog/bin/stardog-admin db create -n drafter-client-test --

cd ../drafter-client

sleep 15 # give drafter a few seconds to start up

lein test
