#!/usr/bin/env bash

set -e
set -o pipefail

if [ -z "${SPARQL_QUERY_ENDPOINT}" ] && [ -z "${SPARQL_UPDATE_ENDPOINT}" ] ; then
   echo You must set env vars for SPARQL_UPDATE_ENDPOINT and SPARQL_QUERY_ENDPOINT
   exit 1
fi

cd `dirname $0`

## TEST DRAFTER CLIENT (against Drafter)

cd ../drafter-client

./bin/kaocha --fail-fast

## TEST DRAFTER

cd ../drafter

./bin/kaocha --reporter documentation --fail-fast

clojure -A:dev:spec
